# Generated by Django 4.1.2 on 2022-10-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='drink_name',
        ),
        migrations.AddField(
            model_name='order',
            name='draft_beer',
            field=models.IntegerField(default=0),
        ),
    ]
