# Generated by Django 4.1.2 on 2022-10-14 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersite', '0003_detail_drink_delete_order_detail_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='detail',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
