# Generated by Django 4.1.2 on 2022-10-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersite', '0004_detail_created_at_detail_price_detail_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='price',
            field=models.IntegerField(default=1000),
        ),
    ]
